-- MySQL Script generated by MySQL Workbench
-- Sun Nov 16 18:45:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ba_sectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ba_sectores` (
  `id_sector` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ba_horarios_turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ba_horarios_turno` (
  `id_horarios_turno` INT NOT NULL AUTO_INCREMENT,
  `turno_id` INT NULL,
  `hora_entrada` TIME NULL,
  `hora_salida` TIME NULL,
  `es_verano` BIT NULL,
  `descripcion` VARCHAR(45) NULL,
  `sector_id` INT NOT NULL,
  PRIMARY KEY (`id_horarios_turno`),
  INDEX `fk_ba_horarios_turno_ba_sectores1_idx` (`sector_id` ASC) VISIBLE,
  CONSTRAINT `fk_ba_horarios_turno_ba_sectores1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `mydb`.`ba_sectores` (`id_sector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ba_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ba_usuarios` (
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `es_admin` BIT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ba_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ba_auditoria` (
  `id_auditoria` INT NOT NULL,
  `accion` VARCHAR(20) NULL,
  `usuario_id` INT NULL,
  `fecha_hora` DATETIME NULL,
  PRIMARY KEY (`id_auditoria`),
  INDEX `fk_ba_auditoria_ba_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_ba_auditoria_ba_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`ba_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ba_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ba_empleados` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `legajo` INT NULL,
  `sector_id` INT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_ba_empleados_ba_sectores1_idx` (`sector_id` ASC) VISIBLE,
  CONSTRAINT `fk_ba_empleados_ba_sectores1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `mydb`.`ba_sectores` (`id_sector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ba_fichadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ba_fichadas` (
  `id_fichadas` INT NOT NULL,
  `empleado_id` INT NULL,
  `hora_entrada` DATETIME NULL,
  `hora_salida` DATETIME NULL,
  `horario_turno_id` INT NULL,
  `horas_totales` INT NULL,
  `trabajadas` INT NULL,
  `extras` INT NULL,
  `adicionales` INT NULL,
  `codigo_novedad` VARCHAR(15) NULL,
  PRIMARY KEY (`id_fichadas`),
  INDEX `fk_ba_fichadas_ba_horarios_turno1_idx` (`horario_turno_id` ASC) VISIBLE,
  INDEX `fk_ba_fichadas_ba_empleados1_idx` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_ba_fichadas_ba_horarios_turno1`
    FOREIGN KEY (`horario_turno_id`)
    REFERENCES `mydb`.`ba_horarios_turno` (`id_horarios_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ba_fichadas_ba_empleados1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `mydb`.`ba_empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
